//Student: Jake Elliott//
//Student #040732505//
//Class: CST2335//
//Creation Date: 25/3/24//
//Group Members: Jake Elliott, Gabriel Hubert, Shilpi Sarkar, Piyalee Mangaraj//
//Project: Final Group Project//
//App: Sunrise/Sunset App//

package algonquin.cst2335.android_group_project;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents the data entity for storing sunrise and sunset times along with geographical coordinates.
 * This class uses Room persistence library annotations to define a table for storing
 * sunrise and sunset data. Each instance of this class represents a row in the table.
 */
@Entity(tableName = "sunrise_data")
public class Sunrise_Data {
    /**
     * Unique ID for the database entry. This is auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    public int id;

    /**
     * Latitude coordinate of the location.
     */
    @ColumnInfo(name = "latitude")
    protected String latitude;

    /**
     * Longitude coordinate of the location.
     */
    @ColumnInfo(name = "longitude")
    protected String longitude;

    /**
     * Time of sunrise for the specified location.
     */
    @ColumnInfo(name = "sunrise_time")
    protected String sunriseTime;

    /**
     * Time of sunset for the specified location.
     */
    @ColumnInfo(name = "sunset_time")
    protected String sunsetTime;

    /**
     * Gets the latitude of the location.
     * @return Latitude of the location.
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * Sets the latitude of the location.
     * @param latitude Latitude to set for the location.
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * Gets the longitude of the location.
     * @return Longitude of the location.
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * Sets the longitude of the location.
     * @param longitude Longitude to set for the location.
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * Gets the sunrise time for the location.
     * @return Sunrise time for the location.
     */
    public String getSunriseTime() {
        return sunriseTime;
    }

    /**
     * Sets the sunrise time for the location.
     * @param sunriseTime Sunrise time to set for the location.
     */
    public void setSunriseTime(String sunriseTime) {
        this.sunriseTime = sunriseTime;
    }

    /**
     * Gets the sunset time for the location.
     * @return Sunset time for the location.
     */
    public String getSunsetTime() {
        return sunsetTime;
    }

    /**
     * Sets the sunset time for the location.
     * @param sunsetTime Sunset time to set for the location.
     */
    public void setSunsetTime(String sunsetTime) {
        this.sunsetTime = sunsetTime;
    }
}
